spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gyhqq/store-config.git
  rabbitmq:
    host: 192.168.232.131
    virtual-host: /gyhqq
    username: gyhqq
    password: gyhqq
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 12000
