server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///store?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.232.131
    virtual-host: /gyhqq
    username: gyhqq
    password: gyhqq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#myBatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
  mapper-locations: classpath*:mapper/**Mapper.xml        #.xml目录
  type-aliases-package: com.store.order.mapper            #接口包
gyh:
  jwt:
    user:
      cookieName: GYH_TOKEN   # cookie名称
      cookieDomain: gyhqq.xyz # cookie的域
  worker:
    workerId: 1
    dataCenterId: 1
