server:
  port: 8084
spring:
  application:
    name: page-service
    #把thymeleaf 缓存关闭
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.232.131
    virtual-host: /gyhqq
    username: gyhqq
    password: gyhqq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
